#Build Docker image from this base image
FROM mongo:4.4.2-bionic

#Expose the mongo db port for inner network & localhost(have to forward the port when running -p 27017:27017) 
#to access
EXPOSE 27017